// Internal Imports
import { useEffect, useState } from "react";
import Head from "next/head";
import dynamic from "next/dynamic";
// Components
import Layout from "@/components/layout/Layout";
import Loader from "@/components/Loader";
import InnerBanner from "@/components/InnerBanner";
// Data
import globalData from "@/utils/data.json";
import WhoWeAre from "@/components/about/whoWeAre";
import { Box, Container, Grid } from "@mui/material";
import InnerTitle from "@/components/InnerTitle";
import Image from "next/image";

const Certificates = ({ locale, data }) => {
  const {
    resources,
    home: { Banner, AboutSection },
  } = data;
  const { headerLinks, footerLinks, socialIcons } = globalData;

  const [loading, setLoading] = useState(true);
  useEffect(() => setLoading(false), []);

  if (loading) return <Loader />;

  return (
    <>
      <Head>
        <title>Buna Construction</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout
        headerLinks={headerLinks}
        footerLinks={footerLinks}
        socialIcons={socialIcons}
        locale={locale}
      >
        <main>
          <InnerBanner title="About" />
          <Box pt={10} pb={10}>
            <Container>
              <Grid container spacing={3} display="flex">
                <Grid item xs={12} md={6}>
                  <InnerTitle title="ISO 9001" align="left" />
                  <h4 className="inner-subtitle">
                    QUALITY MANAGEMENT SYSTEM CERTIFICATE <br />
                    ISO 9001 : 2015
                  </h4>
                  <div className="thumbnail1">
                    <Image
                      width={560}
                      height={700}
                      alt="complex"
                      src="/images/ISO-9001.jpg"
                      priority
                      style={{
                        objectFit: "contain",
                        objectPosition: "left",
                        width: "100%",
                        marginTop: "10px",
                      }}
                    />
                  </div>
                </Grid>

                <Grid item xs={12} md={6}>
                  <InnerTitle title="ISO 45001" align="left" />
                  <h4 className="inner-subtitle">
                    OCCUPATIONAL HEALTH & SAFETY MANAGEMENT SYSTEM CERTIFICATE
                    ISO 45001 : 2018
                  </h4>
                  <div className="thumbnail1">
                    <Image
                      width={560}
                      height={700}
                      alt="complex"
                      src="/images/ISO-4500.jpg"
                      priority
                      style={{
                        objectFit: "contain",
                        objectPosition: "left",
                        width: "100%",
                        marginTop: "10px",
                      }}
                    />
                  </div>
                </Grid>
              </Grid>
            </Container>
          </Box>
        </main>
      </Layout>
    </>
  );
};
export default Certificates;

export const getServerSideProps = async ({ locale }) => {
  const res = await fetch(`${process.env.API_URL}`);
  const data = await res.json();

  return {
    props: {
      data,
      locale,
    },
  };
};
