// Internal Imports
import { useEffect, useState } from "react";
import Head from "next/head";
import dynamic from "next/dynamic";
// Components
import Layout from "@/components/layout/Layout";
import Loader from "@/components/Loader";
import InnerBanner from "@/components/InnerBanner";
// Data
import globalData from "@/utils/data.json";
import { Box, Container } from "@mui/material";
import Image from "next/image";
import InnerTitle from "@/components/InnerTitle";

const clientsImg = [
  {
    id: 1,
    img: "/images/clients/baytur.webp",
    name: "Clients",
  },
  {
    id: 2,
    img: "/images/clients/aou.webp",
    name: "Clients",
  },
  {
    id: 3,
    img: "/images/clients/hec.webp",
    name: "Clients",
  },
  {
    id: 5,
    img: "/images/clients/dac.webp",
    name: "Clients",
  },
  {
    id: 6,
    img: "/images/clients/buna.webp",
    name: "Clients",
  },
  {
    id: 7,
    img: "/images/clients/cdms.webp",
    name: "Clients",
  },
  {
    id: 8,
    img: "/images/clients/sumou.webp",
    name: "Clients",
  },
  {
    id: 9,
    img: "/images/clients/aho.jpg",
    name: "Clients",
  },
  {
    id: 10,
    img: "/images/clients/align-management.png",
    name: "Clients",
  },
  {
    id: 11,
    img: "/images/clients/Asmou-Logo.jpg",
    name: "Clients",
  },
  {
    id: 12,
    img: "/images/clients/logo.jpg",
    name: "Clients",
  },
  {
    id: 13,
    img: "/images/clients/Logo-New-2.jpg",
    name: "Clients",
  },
  {
    id: 14,
    img: "/images/clients/marko.jpg",
    name: "Clients",
  },
  {
    id: 15,
    img: "/images/clients/Musharaka-Capital.jpg",
    name: "Clients",
  },
  {
    id: 16,
    img: "/images/clients/OSG-Contracting.jpg",
    name: "Clients",
  },
  {
    id: 17,
    img: "/images/clients/royal.jpg",
    name: "Clients",
  },
  {
    id: 18,
    img: "/images/clients/Saudi-Aramco-logo.jpg",
    name: "Clients",
  },
  {
    id: 19,
    img: "/images/clients/TAAM-LOGO.jpg",
    name: "Clients",
  },
  {
    id: 20,
    img: "/images/clients/Yusuf-Bin-Ahmed-Kanoo.jpg",
    name: "Clients",
  },
];

const Clients = ({ locale, data }) => {
  const {
    resources,
    home: { Banner, AboutSection },
  } = data;
  const { headerLinks, footerLinks, socialIcons } = globalData;

  const [loading, setLoading] = useState(true);
  useEffect(() => setLoading(false), []);

  if (loading) return <Loader />;

  return (
    <>
      <Head>
        <title>Buna Construction</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout
        headerLinks={headerLinks}
        footerLinks={footerLinks}
        socialIcons={socialIcons}
        locale={locale}
      >
        <main>
          <InnerBanner title="About" />
          <Box
            pt={5}
            pb={2}
            bgcolor="#fff"
            position="relative"
            zIndex={9}
            margin="0 auto 0px"
          >
            <Container>
              <InnerTitle title="Key Clients" align="left" />
            </Container>
            <div
              style={{
                backgroundColor: "#fff",
                width: "80%",
                zIndex: 99,
                position: "relative",
                padding: " 0 10px",
                margin: "auto",
                display: "flex",
                flexWrap: "wrap",
                marginBottom:"30px"
              }}
            >
              {clientsImg?.map((item) => (
                <div
                  key={item.id}
                  className="card-img"
                  style={{
                    width: "130px",
                    height: "100px",
                    margin: "10px",
                    flex: "0 0 23%",
                    border: "1px solid #eee",
                    padding: "10px 0",
                  }}
                >
                  <Image
                    src={item.img}
                    alt={item.name}
                    width={150}
                    height={100}
                    style={{
                      objectFit: "contain",
                      width: "100%",
                      height: "100%",
                    }}
                  />
                </div>
              ))}
            </div>
          </Box>
        </main>
      </Layout>
    </>
  );
};
export default Clients;

export const getServerSideProps = async ({ locale }) => {
  const res = await fetch(`${process.env.API_URL}`);
  const data = await res.json();

  return {
    props: {
      data,
      locale,
    },
  };
};
