// Internal Imports
import { useEffect, useState } from "react";
import Head from "next/head";
import dynamic from "next/dynamic";
// Components
import Layout from "@/components/layout/Layout";
import Loader from "@/components/Loader";
import InnerBanner from "@/components/InnerBanner";
// Data
import globalData from "@/utils/data.json";
import Accordion from "@mui/material/Accordion";
import AccordionSummary from "@mui/material/AccordionSummary";
import AccordionDetails from "@mui/material/AccordionDetails";
import Typography from "@mui/material/Typography";
import ExpandMoreIcon from "@mui/icons-material/ExpandMore";
import styled from "@emotion/styled";
import { Box, Container, Grid } from "@mui/material";

const AccordionStyle = styled(Accordion)({
  marginBottom: "20px",
  borderLeft: "4px solid #10584d",
  boxShadow: "unset",
  "&:before": {
    content: "none",
  },
  "& .MuiAccordionSummary-root": {
    background: "#f8f8f8",
    "&:before": {
      boxShadow: "unset",
    },
  },
  "& h6": {
    fontSize: "18px",
    fontWeight: "bold",
  },
  "& h6:hover": {
    color: "#10584d",
  },
});
const Faq = ({ locale, data }) => {
  const {
    resources,
    home: { Banner, AboutSection },
  } = data;
  const { headerLinks, footerLinks, socialIcons } = globalData;

  const [loading, setLoading] = useState(true);
  useEffect(() => setLoading(false), []);

  if (loading) return <Loader />;

  return (
    <>
      <Head>
        <title>Buna Construction</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout
        headerLinks={headerLinks}
        footerLinks={footerLinks}
        socialIcons={socialIcons}
        locale={locale}
      >
        <main>
          <InnerBanner title="About" />
          <Box flexGrow={1} pt={10} pb={1}>
            <Container fixed>
              <Grid container spacing={3} mb={7} justifyContent="center">
                <Grid item xs={12} md={10} position="relative">
                  <AccordionStyle mb={5}>
                    <AccordionSummary
                      expandIcon={<ExpandMoreIcon />}
                      aria-controls="panel1a-content"
                    >
                      <Typography variant="h6" component="h6">
                        FAQ Question One?
                      </Typography>
                    </AccordionSummary>
                    <AccordionDetails>
                      <Typography variant="body1" component="p">
                        Lorem ipsum dolor sit amet, consectetur adipisicing
                        elit, sed do eiusmod tempor incididunt ut labore et
                        dolore.
                      </Typography>
                    </AccordionDetails>
                  </AccordionStyle>
                  <AccordionStyle mb={5}>
                    <AccordionSummary
                      expandIcon={<ExpandMoreIcon />}
                      aria-controls="panel1a-content"
                    >
                      <Typography variant="h6" component="h6">
                        FAQ Question Two?
                      </Typography>
                    </AccordionSummary>
                    <AccordionDetails>
                      <Typography variant="body1" component="p">
                        Lorem ipsum dolor sit amet, consectetur adipisicing
                        elit, sed do eiusmod tempor incididunt ut labore et
                        dolore.
                      </Typography>
                    </AccordionDetails>
                  </AccordionStyle>
                  <AccordionStyle mb={5}>
                    <AccordionSummary
                      expandIcon={<ExpandMoreIcon />}
                      aria-controls="panel1a-content"
                    >
                      <Typography variant="h6" component="h6">
                        FAQ Question Three?
                      </Typography>
                    </AccordionSummary>
                    <AccordionDetails>
                      <Typography variant="body1" component="p">
                        Lorem ipsum dolor sit amet, consectetur adipisicing
                        elit, sed do eiusmod tempor incididunt ut labore et
                        dolore.
                      </Typography>
                    </AccordionDetails>
                  </AccordionStyle>
                </Grid>
              </Grid>
            </Container>
          </Box>
        </main>
      </Layout>
    </>
  );
};
export default Faq;

export const getServerSideProps = async ({ locale }) => {
  const res = await fetch(`${process.env.API_URL}`);
  const data = await res.json();

  return {
    props: {
      data,
      locale,
    },
  };
};
