// Internal Imports
import Head from "next/head";
// Components
import Layout from "@/components/layout/Layout";
import AboutSec from "@/components/home/aboutSec";
import HomeSlider from "@/components/home/homeSlider";
import BunaSubsidiary from "@/components/home/bunaSubsidiary";
import ProjectSec from "@/components/home/projectSec";
import ClientsSec from "@/components/home/clientsSec";
import CertificateSec from "@/components/home/certificateSec";
// Data
import globalData from "@/utils/data.json";
import ContactSec from "@/components/home/contactSec";


const Home = ({ data , locale}) => {
  const { resources, home: { Banner, AboutSection } } = data;
  const { headerLinks, footerLinks, socialIcons } = globalData;

  return (
    <>
      <Head>
        <title>Buna Construction</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout headerLinks={headerLinks} footerLinks={footerLinks} socialIcons={socialIcons} locale={locale}>
        <main>
          <HomeSlider data={Banner} />
          <AboutSec data={AboutSection} />
          <BunaSubsidiary />
          <ProjectSec locale={locale} />
          <CertificateSec />
          <ContactSec />
          <ClientsSec locale={locale} />
        </main>
      </Layout>
    </>
  )
}
export default Home;


export const getServerSideProps = async ({ locale }) => {
  const res = await fetch(`${process.env.API_URL}`);
  const data = await res.json();

  return {
    props: {
      data,
      locale
    }
  }
}