// Internal Imports
import { useEffect, useState } from "react";
import Head from "next/head";
import dynamic from "next/dynamic";
// Components
import Layout from "@/components/layout/Layout";
import Loader from "@/components/Loader";
import InnerBanner from "@/components/InnerBanner";
// Data
import globalData from "@/utils/data.json";
import {
  Box,
  Typography,
  Card,
  CardMedia,
  CardContent,
  Container,
  Grid,
} from "@mui/material";
import Link from "next/link";
import Image from "next/image";
import AppsIcon from "@mui/icons-material/Apps";

import ArrowBackIosNewOutlinedIcon from "@mui/icons-material/ArrowBackIosNewOutlined";
import ArrowForwardIosOutlinedIcon from "@mui/icons-material/ArrowForwardIosOutlined";

const InnerNews = ({ locale, data }) => {
  const {
    resources,
    home: { Banner, AboutSection },
  } = data;
  const { headerLinks, footerLinks, socialIcons } = globalData;

  const [loading, setLoading] = useState(true);
  useEffect(() => setLoading(false), []);

  if (loading) return <Loader />;

  return (
    <>
      <Head>
        <title>Buna Construction</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout
        headerLinks={headerLinks}
        footerLinks={footerLinks}
        socialIcons={socialIcons}
        locale={locale}
      >
        <main>
          <Box
            flexGrow={1}
            pt={15}
            pb={15}
            bgcolor="#f8f8f8"
            dir="ltr"
            className="multi"
          >
            <Container fixed>
              <Grid container spacing={3} justifyContent="center">
                <Grid item xs={12} md={11}>
                  <Card sx={{ borderRadius: 0, boxShadow: "unset" }}>
                    <CardMedia
                      sx={{ height: "500px", overflow: "hidden" }}
                      className="card-img"
                    >
                      <Image
                        src="/images/02.jpg"
                        width={1200}
                        height={500}
                        alt="news"
                      />
                    </CardMedia>
                    <CardContent
                      sx={{ padding: "50px 35px 30px", position: "relative" }}
                    >
                      <Link href="#">
                        <Box
                          display="flex"
                          justifyContent="space-between"
                          alignItems="center"
                          mb={2}
                          fontSize={16}
                        >
                          <Typography display="flex" alignItems="center">
                            23rd March 2019
                          </Typography>
                        </Box>
                        <Typography
                          variant="h4"
                          component="h4"
                          mb={2}
                          sx={{ "&:hover": { color: "primary.main" } }}
                        >
                          Each of our 8 double rooms has its own distinct Each
                          of our 8 double rooms has its own distinct.
                        </Typography>
                      </Link>
                      <Typography variant="body1" component="p" pb={4}>
                        Lorem ipsum dolor sit amet, consectetur adipisicing
                        elit, sed do eiusmod tempor incididunt ut labore et
                        dolore.Lorem ipsum dolor sit amet, consectetur
                        adipisicing elit, sed do eiusmod tempor incididunt ut
                        labore et dolore.Lorem ipsum dolor sit amet, consectetur
                        adipisicing elit, sed do eiusmod tempor incididunt ut
                        labore et dolore.Lorem ipsum dolor sit amet, consectetur
                        adipisicing elit, sed do eiusmod tempor incididunt ut
                        labore et dolore.Lorem ipsum dolor sit amet, consectetur
                        adipisicing elit, sed do eiusmod tempor incididunt ut
                        labore et dolore.Lorem ipsum dolor sit amet, consectetur
                        adipisicing elit, sed do eiusmod tempor incididunt ut
                        labore et dolore.Lorem ipsum dolor sit amet, consectetur
                        adipisicing elit, sed do eiusmod tempor incididunt ut
                        labore et dolore.
                      </Typography>
                      <Typography variant="body1" component="p">
                        Lorem ipsum dolor sit amet, consectetur adipisicing
                        elit, sed do eiusmod tempor incididunt ut labore et
                        dolore.Lorem ipsum dolor sit amet, consectetur
                        adipisicing elit, sed do eiusmod tempor incididunt ut
                        labore et dolore.Lorem ipsum dolor sit amet, consectetur
                        adipisicing elit, sed do eiusmod tempor incididunt ut
                        labore et dolore.Lorem ipsum dolor sit amet, consectetur
                        adipisicing elit, sed do eiusmod tempor incididunt ut
                        labore et dolore.Lorem ipsum dolor sit amet, consectetur
                        adipisicing elit, sed do eiusmod tempor incididunt ut
                        labore et dolore.Lorem ipsum dolor sit amet, consectetur
                        adipisicing elit, sed do eiusmod tempor incididunt ut
                        labore et dolore.Lorem ipsum dolor sit amet, consectetur
                        adipisicing elit, sed do eiusmod tempor incididunt ut
                        labore et dolore.
                      </Typography>
                    </CardContent>
                    <Box
                      display="flex"
                      justifyContent="space-between"
                      alignItems="center"
                      flexWrap={"nowrap"}
                      mb={2}
                      sx={{ flexDirection: { xs: "column", sm: "row" } }}
                    >
                      <CardMedia>
                        <Image
                          src="/images/news1.jpg"
                          width={300}
                          height={300}
                          alt="news"
                        />
                      </CardMedia>
                      <CardContent
                        sx={{ padding: "50px 35px 30px", position: "relative" }}
                      >
                        <Typography
                          variant="h4"
                          component="h4"
                          mb={2}
                          sx={{ "&:hover": { color: "primary.main" } }}
                        >
                          Each of our 8 double rooms has its own distinct Each
                          of our 8 double rooms has its own distinct.
                        </Typography>
                        <Typography variant="body1" component="p">
                          Lorem ipsum dolor sit amet, consectetur adipisicing
                          elit, sed do eiusmod tempor incididunt ut labore et
                          dolore.Lorem ipsum dolor sit amet, consectetur
                          adipisicing elit, sed do eiusmod tempor incididunt ut
                          labore et dolore.Lorem ipsum dolor sit amet,
                          consectetur adipisicing elit, sed do eiusmod tempor
                          incididunt ut labore et dolore.
                        </Typography>
                      </CardContent>
                    </Box>
                    <CardContent
                      sx={{ padding: "50px 35px 30px", position: "relative" }}
                    >
                      <Typography variant="body1" component="p" pb={4}>
                        Lorem ipsum dolor sit amet, consectetur adipisicing
                        elit, sed do eiusmod tempor incididunt ut labore et
                        dolore.Lorem ipsum dolor sit amet, consectetur
                        adipisicing elit, sed do eiusmod tempor incididunt ut
                        labore et dolore.Lorem ipsum dolor sit amet, consectetur
                        adipisicing elit, sed do eiusmod tempor incididunt ut
                        labore et dolore.Lorem ipsum dolor sit amet, consectetur
                        adipisicing elit, sed do eiusmod tempor incididunt ut
                        labore et dolore.Lorem ipsum dolor sit amet, consectetur
                        adipisicing elit, sed do eiusmod tempor incididunt ut
                        labore et dolore.Lorem ipsum dolor sit amet, consectetur
                        adipisicing elit, sed do eiusmod tempor incididunt ut
                        labore et dolore.Lorem ipsum dolor sit amet, consectetur
                        adipisicing elit, sed do eiusmod tempor incididunt ut
                        labore et dolore.
                      </Typography>
                      <Typography variant="body1" component="p">
                        Lorem ipsum dolor sit amet, consectetur adipisicing
                        elit, sed do eiusmod tempor incididunt ut labore et
                        dolore.Lorem ipsum dolor sit amet, consectetur
                        adipisicing elit, sed do eiusmod tempor incididunt ut
                        labore et dolore.Lorem ipsum dolor sit amet, consectetur
                        adipisicing elit, sed do eiusmod tempor incididunt ut
                        labore et dolore.Lorem ipsum dolor sit amet, consectetur
                        adipisicing elit, sed do eiusmod tempor incididunt ut
                        labore et dolore.Lorem ipsum dolor sit amet, consectetur
                        adipisicing elit, sed do eiusmod tempor incididunt ut
                        labore et dolore.Lorem ipsum dolor sit amet, consectetur
                        adipisicing elit, sed do eiusmod tempor incididunt ut
                        labore et dolore.Lorem ipsum dolor sit amet, consectetur
                        adipisicing elit, sed do eiusmod tempor incididunt ut
                        labore et dolore.
                      </Typography>
                    </CardContent>
                  </Card>
                  <Box
                    flexGrow={1}
                    pt={3}
                    pb={3}
                    pr={2}
                    pl={2}
                    bgcolor="#f6f6f6"
                    display="flex"
                    justifyContent="space-between"
                    alignItems="center"
                    sx={{
                      "& a": { display: "flex", transition: ".3s" },
                      "& a:hover": { color: "#10584d" },
                      "& a:hover >svg": { padding: "3px", transition: ".3s" },
                    }}
                  >
                    <Link href="/" sx={{ display: "flex" }}>
                      <ArrowBackIosNewOutlinedIcon /> <span>Prev Project</span>
                    </Link>
                    <Link href="/projects">
                      <AppsIcon />
                    </Link>
                    <Link href="/">
                      <span>Next Project</span>
                      <ArrowForwardIosOutlinedIcon />
                    </Link>
                  </Box>
                </Grid>
              </Grid>
            </Container>
          </Box>
        </main>
      </Layout>
    </>
  );
};
export default InnerNews;

export const getServerSideProps = async ({ locale }) => {
  const res = await fetch(`${process.env.API_URL}`);
  const data = await res.json();

  return {
    props: {
      data,
      locale,
    },
  };
};
