// Internal Imports
import { useEffect, useState } from "react";
import Head from "next/head";
import dynamic from "next/dynamic";
// Components
import Layout from "@/components/layout/Layout";
import Loader from "@/components/Loader";

// MUI
import Box from "@mui/material/Box";
import Container from "@mui/material/Container";
// Image
import dots from "/public/images/dot-corner.png";
// Data
import globalData from "@/utils/data.json";
import InnerTitle from "@/components/InnerTitle";
import { Grid, styled } from "@mui/material";
// import Swiper core and required modules
import { Swiper, SwiperSlide } from "swiper/react";
import { Navigation, EffectFade, Keyboard, Autoplay } from "swiper";
// Import Swiper styles
import "swiper/css";
import "swiper/css/navigation";
import "swiper/css/effect-fade";
import Image from "next/image";
import Link from "next/link";
import ArrowBackIosNewOutlinedIcon from "@mui/icons-material/ArrowBackIosNewOutlined";
import ArrowForwardIosOutlinedIcon from "@mui/icons-material/ArrowForwardIosOutlined";
import AppsIcon from "@mui/icons-material/Apps";
import AccessTimeIcon from "@mui/icons-material/AccessTime";
import PlaceIcon from "@mui/icons-material/Place";
import CrisisAlertIcon from "@mui/icons-material/CrisisAlert";
import ArchitectureIcon from "@mui/icons-material/Architecture";
import PersonIcon from "@mui/icons-material/Person";
import AttachMoneyIcon from "@mui/icons-material/AttachMoney";
import DescriptionIcon from "@mui/icons-material/Description";
import InnerBanner from "@/components/InnerBanner";

const bannerData = [
  {
    id: 1,
    url: "/images/01.jpg",
    title_en: "BUNA | CONSTRUCTION INTO A NEW FRONTIER",
  },
  {
    id: 2,
    url: "/images/02.jpg",
    title_en: "BUNA | CONSTRUCTION INTO A NEW FRONTIER",
  },
  {
    id: 3,
    url: "/images/03.jpg",
    title_en: "BUNA | CONSTRUCTION INTO A NEW FRONTIER",
  },
];

const InnerProject = ({ locale, data }) => {
  const {
    resources,
    home: { Banner, AboutSection },
  } = data;
  const { headerLinks, footerLinks, socialIcons } = globalData;

  const [loading, setLoading] = useState(true);
  useEffect(() => setLoading(false), []);

  if (loading) return <Loader />;

  return (
    <>
      <Head>
        <title>Buna Construction</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout
        headerLinks={headerLinks}
        footerLinks={footerLinks}
        socialIcons={socialIcons}
        locale={locale}
      >
        <main>
          <InnerBanner title="projects" />
          <Box
            pt={15}
            pb={10}
            className="project-setion"
            sx={{
              backgroundImage: `url(${dots.src})`,
              backgroundRepeat: "no-repeat",
              backgroundPosition: "bottom right",
            }}
          >
            <Container>
              <InnerTitle title="SUMOU GATE" align="left" />

              <Grid
                container
                spacing={3}
                display="flex"
                justifyContent="center"
              >
                <Grid item xs={12} md={12}>
                  <Swiper
                    className="main-slider"
                    modules={[Navigation, EffectFade, Keyboard, Autoplay]}
                    spaceBetween={50}
                    slidesPerView={1}
                    effect={"fade"}
                    keyboard={{
                      enabled: true,
                    }}
                    autoplay={{
                      delay: 7000,
                      disableOnInteraction: false,
                    }}
                    loop={true}
                    navigation
                    pagination={{ clickable: true }}
                  >
                    {bannerData?.length !== 0 &&
                      bannerData?.map((el) => (
                        <SwiperSlide key={el.id}>
                          <Image
                            src={el.url}
                            alt={el.title_en}
                            width={1800}
                            height={500}
                            priority
                            style={{
                              width: "100%",
                              height: "65vh",
                              objectFit: "cover",
                            }}
                          />
                        </SwiperSlide>
                      ))}
                  </Swiper>
                  <Box
                    pt={2}
                    pb={2}
                    mt={4}
                    mb={10}
                    pl={4}
                    sx={{ borderLeft: "4px solid #10584d" }}
                  >
                    <h4 className="inner-subtitle">Project Brief:</h4>
                    <Grid
                      container
                      spacing={3}
                      display="flex"
                      justifyContent="center"
                    >
                      <Grid item xs={12} md={6}>
                        <ul className="">
                          <li style={{ marginBottom: "10px" }}>
                            <span
                              style={{ color: "#10584d", fontWeight: "600" }}
                            >
                              <PersonIcon
                                sx={{ width: "30px", margin: "-3px 0" }}
                              />{" "}
                              Client:
                            </span>{" "}
                            SUMOU Holding
                          </li>
                          <li style={{ marginBottom: "10px" }}>
                            <span
                              style={{ color: "#10584d", fontWeight: "600" }}
                            >
                              <PlaceIcon
                                sx={{ width: "30px", margin: "-3px 0" }}
                              />
                              Location:
                            </span>{" "}
                            Al Madinah , KSA
                          </li>

                          <li style={{ marginBottom: "10px" }}>
                            <span
                              style={{ color: "#10584d", fontWeight: "600" }}
                            >
                              {" "}
                              <AccessTimeIcon
                                sx={{ width: "30px", margin: "-3px 0" }}
                              />
                              Duration:
                            </span>{" "}
                            2023- Date (In Progress)
                          </li>
                          <li style={{ marginBottom: "10px" }}>
                            <span
                              style={{ color: "#10584d", fontWeight: "600" }}
                            >
                              <ArchitectureIcon
                                sx={{ width: "30px", margin: "-3px 0" }}
                              />
                              Sector:
                            </span>{" "}
                            Mixed Use
                          </li>
                          <li style={{ marginBottom: "10px" }}>
                            <span
                              style={{ color: "#10584d", fontWeight: "600" }}
                            >
                              <CrisisAlertIcon
                                sx={{ width: "30px", margin: "-5px 0" }}
                              />
                              Scope:
                            </span>{" "}
                            BCT General Contracting ALIGN Construction
                            Management
                          </li>
                        </ul>
                      </Grid>
                      <Grid item xs={12} md={6}>
                        <ul className="">
                          <li style={{ marginBottom: "10px" }}>
                            <span
                              style={{
                                color: "#10584d",
                                fontWeight: "600",
                                marginRight: "5px",
                              }}
                            >
                              <AttachMoneyIcon
                                sx={{ width: "30px", margin: "-3px 0" }}
                              />
                              Project Budget:
                            </span>
                            350 Million SAR
                          </li>
                          <li style={{ marginBottom: "10px" }}>
                            <span
                              style={{ color: "#10584d", fontWeight: "600" }}
                            >
                              <DescriptionIcon
                                sx={{ width: "30px", margin: "-3px 0" }}
                              />{" "}
                              Description:
                            </span>
                            <br />
                            <div style={{ paddingLeft: "25px" }}>
                              <b>A mixed-use project consists of:</b>
                              <br />
                              <ul>
                                <li>
                                  Two Towers, each 15 floors, 70 m height.
                                </li>
                                <li>Two Connected Sky Bridges.</li>
                                <li>Shops & Luxury Villas.</li>
                                <li>Outdoor Plaza.</li>
                                <li>770 Parking Spaces.</li>
                              </ul>
                            </div>
                          </li>
                        </ul>
                      </Grid>
                    </Grid>
                  </Box>

                  <Box
                    flexGrow={1}
                    pt={3}
                    pb={3}
                    pr={2}
                    pl={2}
                    bgcolor="#f6f6f6"
                    display="flex"
                    justifyContent="space-between"
                    alignItems="center"
                    sx={{
                      "& a": { display: "flex", transition: ".3s" },
                      "& a:hover": { color: "#10584d" },
                      "& a:hover >svg": { padding: "3px", transition: ".3s" },
                    }}
                  >
                    <Link href="/" sx={{ display: "flex" }}>
                      <ArrowBackIosNewOutlinedIcon /> <span>Prev Project</span>
                    </Link>
                    <Link href="/projects">
                      <AppsIcon />
                    </Link>
                    <Link href="/">
                      <span>Next Project</span>
                      <ArrowForwardIosOutlinedIcon />
                    </Link>
                  </Box>
                </Grid>
              </Grid>
            </Container>
          </Box>
        </main>
      </Layout>
    </>
  );
};
export default InnerProject;

export const getServerSideProps = async ({ locale }) => {
  const res = await fetch(`${process.env.API_URL}`);
  const data = await res.json();

  return {
    props: {
      data,
      locale,
    },
  };
};
