import * as React from "react";
import PropTypes from "prop-types";
import Tabs from "@mui/material/Tabs";
import Tab from "@mui/material/Tab";
import Typography from "@mui/material/Typography";
import Box from "@mui/material/Box";
// Internal Imports
import { useEffect, useState } from "react";
import Head from "next/head";
import dynamic from "next/dynamic";
// Components
import Layout from "@/components/layout/Layout";
import Loader from "@/components/Loader";
import InnerBanner from "@/components/InnerBanner";
// Data
import globalData from "@/utils/data.json";
import { Noto_Sans_Canadian_Aboriginal } from "@next/font/google";
import Align from "@/components/subsidiareas/align";
import BCT from "@/components/subsidiareas/bct";
import Taam from "@/components/subsidiareas/taam";
import Dac from "@/components/subsidiareas/dac";

function TabPanel(props) {
  const { children, value, index, ...other } = props;

  return (
    <div
      role="tabpanel"
      hidden={value !== index}
      id={`simple-tabpanel-${index}`}
      aria-labelledby={`simple-tab-${index}`}
      {...other}
    >
      {value === index && (
        <Box>
          <Typography>{children}</Typography>
        </Box>
      )}
    </div>
  );
}

TabPanel.propTypes = {
  children: PropTypes.node,
  index: PropTypes.number.isRequired,
  value: PropTypes.number.isRequired,
};

function a11yProps(index) {
  return {
    id: `simple-tab-${index}`,
    "aria-controls": `simple-tabpanel-${index}`,
  };
}

const Subsidiareas = ({ locale, data }) => {
  const {
    resources,
    home: { Banner, AboutSection },
  } = data;
  const { headerLinks, footerLinks, socialIcons } = globalData;

  //   const [loading, setLoading] = useState(true);

  const [value, setValue] = React.useState(0);

  //   useEffect(() => setLoading(false), []);
  //   if (loading) return <Loader />;

  const handleChange = (event, newValue) => {
    setValue(newValue);
  };

  return (
    <>
      <Head>
        <title>Buna Construction</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout
        headerLinks={headerLinks}
        footerLinks={footerLinks}
        socialIcons={socialIcons}
        locale={locale}
      >
        <main>
          <InnerBanner title="Subsidiareas" />
          <Box sx={{ width: "100%" }}>
            <Box sx={{ borderBottom: 1, borderColor: "divider" }}>
              <Tabs
                value={value}
                onChange={handleChange}
                aria-label="basic tabs example"
                centered
                allowScrollButtonsMobile="true"
                TabIndicatorProps={{
                  style: {
                    backgroundColor: "#000",
                  },
                }}
                sx={{
                  "& .Mui-selected": {
                    backgroundColor: (theme) => theme.palette.primary.main,
                    color: (theme) => theme.palette.common.white,
                  },
                  "& .MuiTabs-flexContainer": {
                    flexDirection: { xs: "column", sm: "row" },
                    justifyContent: "space-between",
                  },
                }}
              >
                <Tab
                  sx={{
                    color: "#000",
                    maxWidth: "100%",
                    minWidth: "auto",
                    p: "30px 100px",
                    fontFamily: "inherit",
                    "&.Mui-selected": {
                      color: (theme) => theme.palette.common.white,
                    },
                  }}
                  label="Align Management"
                  {...a11yProps(0)}
                />
                <Tab
                  sx={{
                    color: "#000",
                    maxWidth: "100%",
                    minWidth: "auto",
                    p: "30px 100px",
                    fontFamily: "inherit",
                    "&.Mui-selected": {
                      color: (theme) => theme.palette.common.white,
                    },
                  }}
                  label="BCT Contracting"
                  {...a11yProps(1)}
                />
                <Tab
                  sx={{
                    color: "#000",
                    maxWidth: "100%",
                    minWidth: "auto",
                    p: "30px 100px",
                    fontFamily: "inherit",
                    "&.Mui-selected": {
                      color: (theme) => theme.palette.common.white,
                    },
                  }}
                  label="TAAM Group"
                  {...a11yProps(2)}
                />
                <Tab
                  sx={{
                    color: "#000",
                    maxWidth: "100%",
                    minWidth: "auto",
                    p: "30px 100px",
                    fontFamily: "inherit",
                    "&.Mui-selected": {
                      color: (theme) => theme.palette.common.white,
                    },
                  }}
                  label="DAC Group"
                  {...a11yProps(3)}
                />
              </Tabs>
            </Box>
            <TabPanel value={value} index={0}>
              <Align />
            </TabPanel>
            <TabPanel value={value} index={1}>
              <BCT />
            </TabPanel>
            <TabPanel value={value} index={2}>
              <Taam />
            </TabPanel>
            <TabPanel value={value} index={3}>
              <Dac />
            </TabPanel>
          </Box>
        </main>
      </Layout>
    </>
  );
};
export default Subsidiareas;

export const getServerSideProps = async ({ locale }) => {
  const res = await fetch(`${process.env.API_URL}`);
  const data = await res.json();

  return {
    props: {
      data,
      locale,
    },
  };
};
